// Calls the serverless `/api/generate` endpoint to get a PBS storyboard
// generated by Claude (or OpenAI) on the server, where the API key lives.
//
// On any failure (no key configured, network error, malformed response) the
// caller falls back to the local heuristic generator so the app never stalls.

import { PBS_TIPS_BY_EMOTION } from "./constants.js";

export class AIGenerationError extends Error {
  constructor(message, info = {}) {
    super(message);
    this.name = "AIGenerationError";
    this.info = info;
  }
}

const ENDPOINT = "/api/generate";

export async function generateStepsAI(person, activity, { signal } = {}) {
  let res;
  try {
    res = await fetch(ENDPOINT, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ person, activity }),
      signal,
    });
  } catch (err) {
    throw new AIGenerationError("Network error reaching AI endpoint.", { cause: err });
  }

  if (!res.ok) {
    let body = "";
    try { body = await res.text(); } catch { /* ignore */ }
    throw new AIGenerationError(
      `AI endpoint returned ${res.status}.`,
      { status: res.status, body }
    );
  }

  const data = await res.json();
  if (!data || !Array.isArray(data.steps) || data.steps.length === 0) {
    throw new AIGenerationError("AI endpoint returned an empty storyboard.", { data });
  }

  return normaliseSteps(data.steps);
}

function normaliseSteps(rawSteps) {
  return rawSteps.map((s, i, arr) => {
    const emotion = ["calm", "transition", "active", "reward"].includes(s.emotion)
      ? s.emotion
      : i === 0
      ? "calm"
      : i === arr.length - 1
      ? "reward"
      : "active";
    return {
      n: i + 1,
      title: String(s.title || "").trim() || `Step ${i + 1}`,
      emotion,
      imagePrompt: String(s.imagePrompt || "").trim() ||
        "Calm flat illustration, easy-read pictogram style, soft pastel background",
      pbsTip: String(s.pbsTip || "").trim() || PBS_TIPS_BY_EMOTION[emotion],
      carerGuidance: String(s.carerGuidance || "").trim(),
      nextHint: i < arr.length - 1
        ? String(arr[i + 1].title || "Next step").trim()
        : "All finished",
      body: String(s.title || "").trim(),
      cue: String(s.imagePrompt || "").trim(),
    };
  });
}
