import React, { useCallback, useEffect, useMemo, useState } from "react";
import Sidebar from "./components/Sidebar.jsx";
import Toast from "./components/Toast.jsx";
import AccessibilityPanel from "./components/AccessibilityPanel.jsx";
import { I } from "./components/Icons.jsx";

import Dashboard from "./screens/Dashboard.jsx";
import ProfileForm from "./screens/ProfileForm.jsx";
import ActivityForm from "./screens/ActivityForm.jsx";
import StoryboardPreview from "./screens/StoryboardPreview.jsx";
import ExportScreen from "./screens/ExportScreen.jsx";
import GeneratingScreen from "./screens/GeneratingScreen.jsx";
import PlaceholderScreen from "./screens/PlaceholderScreen.jsx";

import { generateSteps as generateStepsLocal } from "./lib/generateSteps.js";
import { generateStepsAI, AIGenerationError } from "./lib/aiClient.js";
import {
  PALETTES,
  DEFAULT_PERSON,
  DEFAULT_ACTIVITY,
  RECENT,
} from "./lib/constants.js";

const PREF_DEFAULTS = {
  palette: "sage",
  fontSize: "regular",
  highContrast: false,
};

function loadPrefs() {
  try {
    const raw = localStorage.getItem("pbs.prefs");
    if (!raw) return PREF_DEFAULTS;
    return { ...PREF_DEFAULTS, ...JSON.parse(raw) };
  } catch {
    return PREF_DEFAULTS;
  }
}

export default function App() {
  const [route, setRoute] = useState("dashboard");
  const [person, setPerson] = useState(DEFAULT_PERSON);
  const [activity, setActivity] = useState(DEFAULT_ACTIVITY);
  const [steps, setSteps] = useState([]);
  const [generating, setGenerating] = useState(false);
  const [isAiGenerated, setIsAiGenerated] = useState(false);
  const [toast, setToast] = useState(null);
  const [menuOpen, setMenuOpen] = useState(false);

  const [prefs, setPrefs] = useState(loadPrefs);
  const setPref = (k, v) => setPrefs((p) => ({ ...p, [k]: v }));

  // Persist prefs
  useEffect(() => {
    try { localStorage.setItem("pbs.prefs", JSON.stringify(prefs)); } catch { /* ignore */ }
  }, [prefs]);

  // Apply palette + accessibility settings to the document
  useEffect(() => {
    const p = PALETTES[prefs.palette] || PALETTES.sage;
    document.documentElement.style.setProperty("--sage", p.sage);
    document.documentElement.style.setProperty("--sage-deep", p.deep);
    document.documentElement.style.setProperty("--sage-soft", p.soft);
    document.body.classList.toggle("font-lg", prefs.fontSize === "large");
    document.body.classList.toggle("font-xl", prefs.fontSize === "xlarge");
    document.body.classList.toggle("high-contrast", !!prefs.highContrast);
  }, [prefs]);

  // Scroll to top when route changes
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "instant" in window ? "instant" : "auto" });
  }, [route]);

  const showToast = useCallback((next) => {
    const payload = typeof next === "string" ? { message: next } : next;
    setToast(payload);
    window.clearTimeout(showToast._t);
    showToast._t = window.setTimeout(() => setToast(null), 3200);
  }, []);

  const runGeneration = useCallback(async () => {
    setGenerating(true);
    try {
      const aiSteps = await generateStepsAI(person, activity);
      setSteps(aiSteps);
      setIsAiGenerated(true);
      showToast({ message: "Storyboard generated by AI.", kind: "success" });
    } catch (err) {
      const local = generateStepsLocal(person, activity);
      setSteps(local);
      setIsAiGenerated(false);
      if (err instanceof AIGenerationError && err.info?.status === 501) {
        showToast({
          message: "AI key not configured — showing a template-based storyboard.",
          kind: "error",
        });
      } else {
        showToast({
          message: "AI was unavailable — falling back to a template-based storyboard.",
          kind: "error",
        });
      }
    } finally {
      setGenerating(false);
    }
  }, [person, activity, showToast]);

  const regenerate = useCallback(() => {
    runGeneration();
  }, [runGeneration]);

  const goToPreview = useCallback(() => {
    setRoute("preview");
    runGeneration();
  }, [runGeneration]);

  const startNew = () => setRoute("profile");

  const screen = useMemo(() => {
    const props = { onMenu: () => setMenuOpen(true) };
    switch (route) {
      case "dashboard":
        return (
          <Dashboard
            setRoute={setRoute}
            recent={RECENT}
            startNew={startNew}
            topActions={<AccessibilityPanel prefs={prefs} setPref={setPref} />}
            {...props}
          />
        );
      case "profile":
        return (
          <ProfileForm
            data={person}
            setData={setPerson}
            onNext={() => setRoute("activity")}
            onBack={() => setRoute("dashboard")}
            {...props}
          />
        );
      case "activity":
        return (
          <ActivityForm
            data={activity}
            setData={setActivity}
            person={person}
            onNext={goToPreview}
            onBack={() => setRoute("profile")}
            {...props}
          />
        );
      case "preview":
        if (generating) return <GeneratingScreen person={person} activity={activity} {...props} />;
        return (
          <StoryboardPreview
            person={person}
            activity={activity}
            steps={steps}
            setSteps={setSteps}
            regenerate={regenerate}
            onBack={() => setRoute("activity")}
            goExport={() => setRoute("export")}
            showToast={showToast}
            isAiGenerated={isAiGenerated}
            {...props}
          />
        );
      case "export":
        return (
          <ExportScreen
            person={person}
            activity={activity}
            steps={steps}
            onBack={() => setRoute("preview")}
            onDone={() => setRoute("dashboard")}
            showToast={showToast}
            {...props}
          />
        );
      case "clients":
        return <PlaceholderScreen title="People I support" sub="Your caseload across all houses." icon={I.Users} {...props} />;
      case "library":
        return <PlaceholderScreen title="Storyboard library" sub="Templates and saved storyboards from your team." icon={I.Library} {...props} />;
      case "drafts":
        return <PlaceholderScreen title="Drafts" sub="Storyboards you've started but not yet finished." icon={I.Doc} {...props} />;
      case "settings":
        return <PlaceholderScreen title="Settings" sub="Workspace, accessibility and integrations." icon={I.Settings} {...props} />;
      case "help":
        return <PlaceholderScreen title="Help & guidance" sub="PBS resources, training and contact your champion." icon={I.Help} {...props} />;
      default:
        return null;
    }
  }, [route, person, activity, steps, generating, regenerate, goToPreview, showToast, prefs, isAiGenerated]);

  return (
    <div className="app">
      <Sidebar
        route={route}
        setRoute={setRoute}
        draftCount={3}
        open={menuOpen}
        onClose={() => setMenuOpen(false)}
      />
      <main className="main">{screen}</main>
      <Toast toast={toast} />
    </div>
  );
}
